### ISSUE TITLE
server.on is not a function

### ISSUE THREAD

**Issue by Crusader4Christ** [Helidium/Mitol#10]
server.on('connection', callback) leads to error server.on is not a function
same as server.unref()

**Comment by bnlambert** [comment]
+1 I am having the same issues, I hope a fruitful response comes up soon

**Comment by Helidium** [comment]
server.on method is now implemented. Currently 'connection' event is captured. Other will follow soon

**Comment by bnlambert** [comment]
Thanks for the  update. I have been trying to use it with hapi but it seems more methods are needed. At the moment I have no issues running mitol with express.

Keep up with the good work, I hope the stardard http module methods will be available as soon as possible.

Cheers
