### ISSUE TITLE
 '../src/Server.h' file not found

### ISSUE THREAD

**Issue by mattrmiller** [Helidium/Mitol#3]
npm install produces:

```  CXX(target) Release/obj.target/mitol/mns.o
In file included from ../mns.cc:1:
../http.h:10:10: fatal error: '../src/Server.h' file not found
#include "../src/Server.h"
         ^
```
npm: v4.6.1
node: v6.11.1

**Comment by Helidium** [comment]
Hi @mattrmiller, can you please post the full build log. What platform are you testing this on?

Thank you

**Comment by Helidium** [comment]
I have published a new version, can you give it a try?
