### ISSUE TITLE
Can't write 400 status code

### ISSUE THREAD

**Issue by udivankin** [Helidium/Mitol#7]
Here's the code:

```javascript
const http = require('mitol');

let server = http.createServer((req, res) => {
    res.statusCode = 400;
    res.end();
});
 
server.listen(8099, () => {
    console.log('Example app listening on port 8099!')
});
```

Nothing is returned in response (lets say timeout).
When trying to set e.g statusCode = 404, it works as expected.

**Comment by Helidium** [comment]
I have added the missing status code messages. Now it should be possible to set the status message.
